### ISSUE TITLE
Error when a player joins

### ISSUE THREAD

**Issue by XShockinFireX** [CrazedCraft/Extropy#1]
TypeError: "Argument 5 passed to pocketmine\level\format\generic\BaseChunk::__construct() must be of the type array, string given, called in phar://E:/0-FirePE-CTF/PocketMine-MP.phar/src/pocketmine/level/format/anvil/Chunk.php on line 92" (EXCEPTION) in "/src/pocketmine/level/format/generic/BaseChunk" at line 49

Reproduced by joining the server, I can confirm that this isn't a plugin issue.

**Comment by JackNoordhuis** [comment]
This issue is caused when a player attempts to join the server when you're running an Anvil world. Extropy only supports MCRegion worlds, you can use a world converter to convert your worlds to the MCRegion format if you want to use your Anvil worlds with Extropy.

**Comment by XShockinFireX** [comment]
@JackNoordhuis Ah okay, thanks for responding.
